### PR TITLE
Fix build issue in NamePropagate.hs (--enable-name-prop)

### PR DESCRIPTION
**Pull request by ret**
Added missing indentation.

```
blarney> [27 of 39] Compiling Blarney.Netlist.Passes.NamePropagate
blarney>    
blarney> /Users/reto/gh/blarney-examples/shadow-blarney//Users/reto/gh/blarney/Haskell/Blarney/Netlist/Passes/NamePropagate.hs:29:17: error:
blarney>     parse error on input ‘<-’
blarney>     Perhaps this statement should be within a 'do' block?
blarney>    |
blarney> 29 |       isVisited <- readArray visited instId
blarney>    |                 ^^
blarney>    
```

### CODE REVIEW

**Comment by mn416** [comment]
Hi @ret,

Happy to merge this.  I agree, I think there should be space.  Weirdly though, it compiles fine for me with GHC 8.6.5 under Linux.  What version of GHC are you using?

Thanks

**Comment by mn416** [comment]
@gameboo are you ok with the renaming of the `.cabal` file?

**Comment by ret** [comment]
I was using GHC 8.8.4.

**Comment by gameboo** [comment]
Thanks for the fix @ret . @mn416 I also had thing building fine, so presumably newer compiler is stricter there? All in all, happy with the renaming, and happy for you to click merge.

**Comment by ret** [comment]
Awesome! Thank you both. Really appreciate the energy you put into Blarney!

**Comment by mn416** [comment]
Thanks @ret!

**Pull request merged**
