### PR TITLE
Efficient verification

### PR DESCRIPTION
**Pull request by Swire42**
This pull request builds on #135 (#133 + #134), and adds two more key features:
- A new verification scheme, that makes use of quantifiers to significantly reduce the required induction depth.
- A general-purpose, concurrent proof engine.

# New verification scheme

The new verification schemes is meant to be used in place of restricted states induction. It is referred to as "quantified induction" since it uses quantifiers.

Here is a description of the new scheme compared to the previous ones:
- Basic induction (incomplete): Extending a safe n-trace by 1 step always gives a safe (n+1)-trace
- Restricted states induction: Extending a non-looping n-trace by 1 step always gives a safe (n+1) trace
- (New) Quantified induction: If all n-traces starting from a state are safe, so are (n+1)-traces from that state.

Cf [this succinct pdf](https://github.com/blarney-lang/blarney/files/15254654/verif2.pdf) for more details.
The notations are borrowed from "Checking safety properties using induction and a SAT-solver" (TLDR: inputs are "tucked in the states": T(s1, s2) holds iff the state and input in `s1` lead to the state in `s2`, independently of the input in `s2`).
Note: these notations are useful to concisely describe the schemes, they are not implemented this way in `NewSMT.hs`.

# Concurrent proof engine

`verifyCircuit` and its specialization `verifyDefault` allow one to verify assertions using several SMT solver instances at once. They work by collecting solver results until there are enough to emit a conclusion ("verified" or "falsifiable"), or all jobs have completed ("unknown").

For most purposes, `verifyDefault (Verbose, vconfQuiet)` or `verifyDefault (Info, vconfQuiet)` can be used as a one-size-fits-all verification scheme. 

`verifyDefault` uses 8 concurrent `z3` workers: 4 working on bounded verification, and 4 working on quantified induction. The depths increases following a ~geometric sequence with carefully chosen parameters.
(Note: from my experience, using more cores does not provide clear benefits, as verification times grow rapidly with depth)

It is possible to use `verifyCircuit` to achieve more exotic/customized verification strategies, such as working at a fixed depth, using restricted states induction instead of or together with quantified induction, using different depth sequences, or a different number of `z3` workers. Refer to `verifyDefault` for inspiration on how to do so.

# Results

The following results where obtained with `verifyDefault (Verbose, vconfQuiet)` on [Five](https://github.com/blarney-lang/five):

- On commit `6291e25`: 4/5 of the assertions get verified in a few seconds, the remaining "Operands correct" assertion requires several hours of work, but is ultimately also verified (about 10h on my last run, I have however seen it get verified in 5h previously, not sure what changed).
- On commit `844d6f6`: The "Forward progress" properties are correctly shown to be falsifiable, in a few minutes (about 15mins on my computer).

This is a huge success compared to restricted states verification, which to my knowledge is unable to verify any of these assertions in reasonable time.

### CODE REVIEW

**Comment by mn416** [comment]
Thanks @Swire42, I'm currently reproducing the `Five` results. Will get back to you when it's done.

I spoke to @gameboo who did the current SMT backend. He was keen to have only a single backend but, after some discussion, we agreed that it would be good to merge this PR and have two for now: the current one being considered "stable" and the new one "experimental". In time, with more understanding and confidence, we can hopefully return to one.

With this in mind, it may be more appropriate to require an explicit import of `Blarney.Backend.NewSMT` by the user rather than have it exported by default. (I don't mind making this small change.)

The only remaining issue is disallowing partial don't cares in initial register values. I am currently debating whether to go with that or to fix it.

**Comment by mn416** [comment]
@Swire42, I've had a go at preserving don't care values in register initialisers in the [mn416-dontcare-refactor](https://github.com/blarney-lang/blarney/blob/mn416-dontcare-refactor/) branch.

The main changes are:

  * `type InitVal = Ternary`
  * `data Prim = ... Register InitVal InputWidth | RegisterEn InitVal InputWidth`
  * The `Ternary` type is defined [here](https://github.com/blarney-lang/blarney/blob/mn416-dontcare-refactor/Haskell/Blarney/Core/Ternary.hs)

How easy do you think it would be to refactor your PR on top of this branch?

**Comment by Swire42** [comment]
I implemented it on branch [`best-verif-dontcare-refactor`](https://github.com/Swire42/blarneytv/tree/best-verif-dontcare-refactor).
Tested on a small example.
Should I merge it into this pull request? (or create a new independent pull request?)

**Comment by Swire42** [comment]
I have not checked whether it affects performance. Hopefully it does not. But given my recent experiences with z3 I wouldn't be so sure.
If it turns out that it does affect performance, it should be fairly easy to add code to use the previous method whenever possible.

**Comment by mn416** [comment]
@Swire42, wow, great! I will recheck the `Five` properties and get back to you. Will also do a bit more testing, e.g. `FiveAlive`, `SIMTight`.

**Comment by mn416** [comment]
@Swire42, the `Five` properties go through fine on your latest branch (a bit quicker than before). Please go ahead and merge that branch with this PR.

The last remaining issue before merging seems to be the export list. Your proposal sounds good to me: a function that's good for verification, one that's good for debugging, and one for generating SMT files. Would that be much work?

(I've not actually used the new backend for debugging or generating SMT files yet. I will get round to that at some point, but for now I'm happy to go with what you think is sensible.)

**Comment by Swire42** [comment]
Merged the don't care refactor into the pull request.
I'll add a commit cleaning up the export list soon.

**Comment by Swire42** [comment]
I have cleaned up the export list, now only `Verbosity(..)`, `checkAuto`, `checkFixed`, `debugAuto` and `debugFixed` are exported by default.
One can still import the rest with `import Blarney.Backend.NewSMT`.

The only thing I am unhappy with is the `Verbosity(..)` export, because it exports generic names: `Verbose`, `Info` and `Quiet`.
But apparently Haskell cannot reexport qualified modules, so I am not sure what to do here.

Regarding the usage of the new functions:
- `checkAuto Info` is the one-size-fits-all verification procedure. (or `checkAuto Verbose` to get progress reports)
- `checkFixed depth Info` is the same for fixed-depth (therefore more efficient).
- `debugAuto Info` is not focusing on speed, but on producing minimal counter-examples.
- `debugFixed depth Info` is the same for fixed-depth (therefore more efficient).

I have not yet exported functions for writing smtlib files.

**Comment by mn416** [comment]
Great work, thanks @Swire42. Looking forward to using this backend more in future.

**Comment by Swire42** [comment]
It should be fairly easy to write a version that does not rely on async, and just does everything single-threaded.
I'm not sure how to write a switch to enable using one or the other depending on the context though. Maybe you do?
Given the gigantic difference in performance between the old and the new backend, I think it makes sense to have it available to all users, even if it's a degraded version running a single z3 instance at a time.

**Comment by mn416** [comment]
I guess there are a couple of options:

Option 1: Factor out `async`-dependent code from `NewSMT.hs` into `NewSMT/Par.hs`. Require an explicit import of the latter but not the former.

Option 2: Use a CPP macro `ENABLE_PAR_SMT` to decide whether or not to import `Control.Concurrent.Async` and in cabal do something like:

```
flag enable-parallel-smt
  description: Enable parallel SMT solving (depends on the async package)
  manual: True
  default: False

  if flag(enable-parallel-smt)
    ghc-options: -DENABLE_PAR_SMT
    build-depends: async
```

Happy to merge Option 1 this if you'd like to make the necessary changes. Option 2 is a bit more unknown (needs the `CPP` extension), so would have to try it and see how well it works.

**Pull request merged**
