### PR TITLE
Generalize test.sh script to allow testing of other directories/examples

### PR DESCRIPTION
**Pull request by JonasAlaif**
Changes to two variables so that they can be set externally, falling back to a default if not set

### CODE REVIEW

**Comment by JonasAlaif** [comment]
Actually this fails with the array, let me fix that

**Comment by mn416** [comment]
Thanks Jonas

**Comment by mn416** [comment]
@JonasAlaif, I wonder if it should be `BLARNEY_TESTING_ROOT` to avoid potential name clashes in the environment?

**Comment by JonasAlaif** [comment]
@mn416 That's a good point. Maybe a similar change with `EXAMPLES` as well, since that could potentially be set. Not sure what the best name would be there -- `BLARNEY_EXAMPLES`?

**Comment by mn416** [comment]
Yeah I think so, I guess it's good practice to prefix any external env vars with `BLARNEY_`.

**Pull request merged**
