### PR TITLE
The chaining function used for verification was incorrect

### LINKED ISSUE #130: Incorrect verification
There seems to be an issue with (at least) the restricted state verification.
Using the following file (in a template-project context):
```hs
import Blarney

notId :: Bit 1 -> Bit 1
notId x = s
  where
    s = x .^. c
    p = delay 0 $ delay 1 p
    c = delay 0 (p .&. s)

prop :: Bit 1 -> Action ()
prop x = assert (notId x === x) "notId === id"

main :: IO ()
main = do
  verifyWith cnfNoRestr prop
  verifyWith cnfRestr prop
  where
    cnfRestr = dfltVerifyConf { verifyConfMode = Induction (IncreaseFrom 1) True }
    cnfNoRestr = dfltVerifyConf { verifyConfMode = Induction (IncreaseFrom 1) False }
```
I get:
```
Assertion: notId === id
restricted states: disabled
(depth 1) bounded ............ valid
(depth 1) induction step ..... falsifiable
(depth 2) bounded ............ valid
(depth 2) induction step ..... falsifiable
(depth 3) bounded ............ falsifiable
not verified
Assertion: notId === id
restricted states: enabled
(depth 1) bounded ............ valid
(depth 1) induction step ..... falsifiable
(depth 2) bounded ............ valid
(depth 2) induction step ..... valid
verified
```

The `restricted state: disabled` result is correct, but the `restricted state: enabled` is incorrect.

The issue might also be happening with non-restricted states induction, since on this example it is bounded that rejects the property.

### PR DESCRIPTION
**Pull request by Swire42**
The chaining function used for verification was incorrect.
It returned `(_, [state.1, state.2, ..., state.(k+1), state.(k+1)])` instead of the expectable `(_, [state.0, state.1, ..., state.k, state.(k+1)])`.
This in turn made the restricted state condition incorrect, off by one.

This fixes #130

### CODE REVIEW

**Comment by mn416** [comment]
@Swire42 Thanks for reporting this issue and fixing it!

**Comment by mn416** [comment]
@Swire42 I've rolled back this change as it seems that something is not quite right. I will investigate further. Each pair returned by the chaining function holds a boolean and a state, but with your change, these seem to go out of sync.

**Comment by Swire42** [comment]
That is weird, have you found a property that is incorrectly verified?
I'm not entirely sure what you mean by "out of sync", but indeed `k+1` states are returned, and only `k` ok values.

**Comment by mn416** [comment]
I found a property that used to be verified quickly (using depth-bounded verification) but now takes a long time, and can't explain this from the change that was made. This is very strange as depth-bounded verification does not even look at the list of states returned by the chaining function! Perhaps the complex formula  (involving recursive functions) generated by Blarney are just too confusing for z3?

In any case, your change is surely correct, so I will put it back after a bit more exploration.

**Comment by Swire42** [comment]
Indeed, that z3 performance issue is the main reason I wrote the new SMT backend.
The performance issue is surprisingly easy to trigger, you can look at the example I gave on the z3 github issue.

**Pull request merged**
